// <auto-generated />
using Loja_e_commerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loja_e_commerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Loja_e_commerce.Models.Cliente", b =>
                {
                    b.Property<int>("Cod_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_cliente"));

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("num_casa")
                        .HasColumnType("int");

                    b.Property<string>("rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cod_cliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Loja_e_commerce.Models.Clientes.Email", b =>
                {
                    b.Property<int>("Cod_Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Email"));

                    b.Property<int>("Cod_cliente")
                        .HasColumnType("int");

                    b.Property<string>("str_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cod_Email");

                    b.HasIndex("Cod_cliente");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("Loja_e_commerce.Models.Clientes.Telefone", b =>
                {
                    b.Property<int>("Cod_Telefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Telefone"));

                    b.Property<int>("Cod_cliente")
                        .HasColumnType("int");

                    b.Property<string>("str_Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cod_Telefone");

                    b.HasIndex("Cod_cliente");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("Loja_e_commerce.Models.Compra", b =>
                {
                    b.Property<int>("Cod_compra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_compra"));

                    b.Property<int>("Cod_Prod")
                        .HasColumnType("int");

                    b.Property<float>("valor_total")
                        .HasColumnType("real");

                    b.HasKey("Cod_compra");

                    b.HasIndex("Cod_Prod");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("Loja_e_commerce.Models.Estoque", b =>
                {
                    b.Property<int>("Cod_Estoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Estoque"));

                    b.Property<int>("Cod_Funcionario")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Produto")
                        .HasColumnType("int");

                    b.HasKey("Cod_Estoque");

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("Loja_e_commerce.Models.Funcionario", b =>
                {
                    b.Property<int>("Cod_func")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_func"));

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("salario")
                        .HasColumnType("real");

                    b.HasKey("Cod_func");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("Loja_e_commerce.Models.Produto", b =>
                {
                    b.Property<int>("Cod_Prod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cod_Prod"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("preco")
                        .HasColumnType("real");

                    b.Property<int>("qtd_estoque")
                        .HasColumnType("int");

                    b.HasKey("Cod_Prod");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Loja_e_commerce.Models.Clientes.Email", b =>
                {
                    b.HasOne("Loja_e_commerce.Models.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("Cod_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");
                });

            modelBuilder.Entity("Loja_e_commerce.Models.Clientes.Telefone", b =>
                {
                    b.HasOne("Loja_e_commerce.Models.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("Cod_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");
                });

            modelBuilder.Entity("Loja_e_commerce.Models.Compra", b =>
                {
                    b.HasOne("Loja_e_commerce.Models.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("Cod_Prod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("produto");
                });
#pragma warning restore 612, 618
        }
    }
}
